name: ChatLink
main: com.winthier.chatlink.ChatLinkPlugin
version: 0.1
author: StarTux
description: Connect the chat between multiple Bukkit servers
depend: [ WinLink, Vault ]
softdepend: [ Herochat, Winthier ]
commands:
  chatlink:
    description: General purpose command for administrators
    usage: 'Usage: /<command> [command] ...'
    permission: chatlink.cmd
  xmsg:
    aliases: [ xtell, xwhisper ]
    description: Send a private message across servers
    usage: 'Usage: /<command> <player> <message>'
    permission: chatlink.whisper
  xreply:
    aliases: [ xr ]
    description: Reply to last private message across servers
    usage: 'Usage: /<command> <message>'
permissions:
  chatlink.cmd:
    description: Execute the chatlink command
    default: op
  chatlink.whisper:
    description: Send private messages via xmsg, xtell or xwhisper
    default: op
  chatlink.colors:
    description: Use chat colors
    default: op